// <auto-generated />
using DateMeReal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DateMeReal.Migrations
{
    [DbContext(typeof(MovieEntryContext))]
    partial class MovieEntryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("DateMeReal.Models.ApplicationEntry", b =>
                {
                    b.Property<int>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EntryId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            EntryId = 1,
                            Category = "Romance",
                            Director = "Damien Chazelle",
                            Edited = false,
                            MovieName = "La La Land",
                            Notes = "A really good movie that makes you think.",
                            Rating = "PG-13",
                            Year = "2016"
                        },
                        new
                        {
                            EntryId = 2,
                            Category = "Action/Adventure",
                            Director = "Brad Bird",
                            Edited = false,
                            MovieName = "Ratatouille",
                            Notes = "Vibes are unmatched.",
                            Rating = "PG",
                            Year = "2007"
                        },
                        new
                        {
                            EntryId = 3,
                            Category = "Action/Adventure",
                            Director = "Morten Tyldum",
                            Edited = false,
                            MovieName = "The Imitation Game",
                            Notes = "",
                            Rating = "PG-13",
                            Year = "2014"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
